// Copyright 2020 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


syntax = "proto3";

package cirque.proto;

message WeaveCapability {
  string weave_certificate_path = 1;
  string target_path = 2;
}

message ThreadCapability {
  int32 petition_id = 1; // 0 for default behavior
  bool rcp_mode = 2; // False for default behavior
  repeated string daemons = 3; // leave empty for default behavior
}

message WiFiCapability {
  bool use_virtual_wifi_tcp = 1;
  int32 control_port = 2;
  int32 mgmt_port = 3;
  int32 data_port = 4;
  string mac_addr = 5;
  string station_id = 6;
}

message XvncCapability {
  bool localhost = 1;
  int32 display_id = 2; // 0 for auto select
  int32 docker_display_id = 3;
}

message InteractiveCapability {
}

message LanAccessCapability {
  bool internal_lan = 1; // False for default behavior
}

message MountPair {
  string host_path = 1;
  string target_path = 2;
}

message MountCapability {
  repeated MountPair mount_pairs = 1;
}

message TrafficControlCapability {
  int32 latency_ms = 1;
  int32 loss_rate = 2;
}

message BluetoothCapability {
  int32 num_btvirts = 1;
  bool use_virtual_bt_tcp = 2;
  int32 control_port = 3;
  int32 hci_port = 4;
  int32 phy_port = 5;
  string bd_addr = 6;
}

